
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class ItemCfg : Luban.BeanBase
{
    public ItemCfg(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["desc"].IsString) { throw new SerializationException(); }  Desc = _buf["desc"]; }
        { if(!_buf["price"].IsNumber) { throw new SerializationException(); }  Price = _buf["price"]; }
        { if(!_buf["upgrade_to_item_id"].IsNumber) { throw new SerializationException(); }  UpgradeToItemId = _buf["upgrade_to_item_id"]; }
        { if(!_buf["batch_useable"].IsBoolean) { throw new SerializationException(); }  BatchUseable = _buf["batch_useable"]; }
        { if(!_buf["quality"].IsString) { throw new SerializationException(); }  Quality = _buf["quality"]; }
        { if(!_buf["exchange_stream"].IsString) { throw new SerializationException(); }  ExchangeStream = _buf["exchange_stream"]; }
        { if(!_buf["exchange_list"].IsString) { throw new SerializationException(); }  ExchangeList = _buf["exchange_list"]; }
    }

    public static ItemCfg DeserializeItemCfg(JSONNode _buf)
    {
        return new ItemCfg(_buf);
    }

    /// <summary>
    /// 这是id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名字
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 价格
    /// </summary>
    public readonly int Price;
    /// <summary>
    /// 引用当前表
    /// </summary>
    public readonly int UpgradeToItemId;
    /// <summary>
    /// 能否批量使用
    /// </summary>
    public readonly bool BatchUseable;
    /// <summary>
    /// 品质
    /// </summary>
    public readonly string Quality;
    /// <summary>
    /// 道具兑换配置
    /// </summary>
    public readonly string ExchangeStream;
    public readonly string ExchangeList;
   
    public const int __ID__ = -514136015;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "desc:" + Desc + ","
        + "price:" + Price + ","
        + "upgradeToItemId:" + UpgradeToItemId + ","
        + "batchUseable:" + BatchUseable + ","
        + "quality:" + Quality + ","
        + "exchangeStream:" + ExchangeStream + ","
        + "exchangeList:" + ExchangeList + ","
        + "}";
    }
}

}

