
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace Table
{
public sealed partial class AttrConvertCfg : Luban.BeanBase
{
    public AttrConvertCfg(JSONNode _buf) 
    {
        { if(!_buf["index"].IsNumber) { throw new SerializationException(); }  Index = _buf["index"]; }
        { if(!_buf["ProfId"].IsNumber) { throw new SerializationException(); }  ProfId = _buf["ProfId"]; }
        { if(!_buf["Lv1Attr"].IsString) { throw new SerializationException(); }  Lv1Attr = _buf["Lv1Attr"]; }
        { var __json0 = _buf["ConvertMap"]; if(!__json0.IsArray) { throw new SerializationException(); } ConvertMap = new System.Collections.Generic.Dictionary<string, float>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { string _k0;  { if(!__e0[0].IsString) { throw new SerializationException(); }  _k0 = __e0[0]; } float _v0;  { if(!__e0[1].IsNumber) { throw new SerializationException(); }  _v0 = __e0[1]; }  ConvertMap.Add(_k0, _v0); }   }
    }

    public static AttrConvertCfg DeserializeAttrConvertCfg(JSONNode _buf)
    {
        return new AttrConvertCfg(_buf);
    }

    /// <summary>
    /// index
    /// </summary>
    public readonly int Index;
    /// <summary>
    /// 职业ID
    /// </summary>
    public readonly int ProfId;
    /// <summary>
    /// 一级属性ID
    /// </summary>
    public readonly string Lv1Attr;
    /// <summary>
    /// 转换属性
    /// </summary>
    public readonly System.Collections.Generic.Dictionary<string, float> ConvertMap;
   
    public const int __ID__ = 664842914;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "index:" + Index + ","
        + "ProfId:" + ProfId + ","
        + "Lv1Attr:" + Lv1Attr + ","
        + "ConvertMap:" + Luban.StringUtil.CollectionToString(ConvertMap) + ","
        + "}";
    }
}

}

