
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace Table
{
public partial class AttrConvertCfgMgr
{
    private readonly System.Collections.Generic.Dictionary<int, AttrConvertCfg> _dataMap;
    private readonly System.Collections.Generic.List<AttrConvertCfg> _dataList;
    
    public AttrConvertCfgMgr(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, AttrConvertCfg>();
        _dataList = new System.Collections.Generic.List<AttrConvertCfg>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            AttrConvertCfg _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = AttrConvertCfg.DeserializeAttrConvertCfg(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Index, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, AttrConvertCfg> DataMap => _dataMap;
    public System.Collections.Generic.List<AttrConvertCfg> DataList => _dataList;

    public AttrConvertCfg GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public AttrConvertCfg Get(int key) => _dataMap[key];
    public AttrConvertCfg this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

