
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace Table
{
public sealed partial class BulletCfg : Luban.BeanBase
{
    public BulletCfg(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["CollideSkillID"].IsNumber) { throw new SerializationException(); }  CollideSkillID = _buf["CollideSkillID"]; }
        { if(!_buf["BombSkillId"].IsNumber) { throw new SerializationException(); }  BombSkillId = _buf["BombSkillId"]; }
        { if(!_buf["Speed"].IsNumber) { throw new SerializationException(); }  Speed = _buf["Speed"]; }
        { if(!_buf["LifeTime"].IsNumber) { throw new SerializationException(); }  LifeTime = _buf["LifeTime"]; }
        { if(!_buf["collideCount"].IsNumber) { throw new SerializationException(); }  CollideCount = _buf["collideCount"]; }
        { if(!_buf["commonCD"].IsNumber) { throw new SerializationException(); }  CommonCD = _buf["commonCD"]; }
        { if(!_buf["ModelName"].IsString) { throw new SerializationException(); }  ModelName = _buf["ModelName"]; }
        { if(!_buf["ModelScale"].IsNumber) { throw new SerializationException(); }  ModelScale = _buf["ModelScale"]; }
        { if(!_buf["ScriptName"].IsString) { throw new SerializationException(); }  ScriptName = _buf["ScriptName"]; }
        { if(!_buf["ShootAudio"].IsString) { throw new SerializationException(); }  ShootAudio = _buf["ShootAudio"]; }
        { if(!_buf["ExplodeEffect"].IsString) { throw new SerializationException(); }  ExplodeEffect = _buf["ExplodeEffect"]; }
        { if(!_buf["HitEffect"].IsString) { throw new SerializationException(); }  HitEffect = _buf["HitEffect"]; }
    }

    public static BulletCfg DeserializeBulletCfg(JSONNode _buf)
    {
        return new BulletCfg(_buf);
    }

    /// <summary>
    /// 这是id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名字
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 碰撞技能
    /// </summary>
    public readonly int CollideSkillID;
    /// <summary>
    /// 爆炸技能
    /// </summary>
    public readonly int BombSkillId;
    /// <summary>
    /// 速度
    /// </summary>
    public readonly float Speed;
    /// <summary>
    /// 生存时间
    /// </summary>
    public readonly int LifeTime;
    /// <summary>
    /// 碰撞次数
    /// </summary>
    public readonly int CollideCount;
    /// <summary>
    /// 碰撞公共CD
    /// </summary>
    public readonly float CommonCD;
    /// <summary>
    /// 模型
    /// </summary>
    public readonly string ModelName;
    /// <summary>
    /// 模型缩放
    /// </summary>
    public readonly int ModelScale;
    /// <summary>
    /// 子弹脚本
    /// </summary>
    public readonly string ScriptName;
    /// <summary>
    /// 射出音效
    /// </summary>
    public readonly string ShootAudio;
    /// <summary>
    /// 爆炸特效
    /// </summary>
    public readonly string ExplodeEffect;
    /// <summary>
    /// 命中特效
    /// </summary>
    public readonly string HitEffect;
   
    public const int __ID__ = -1027634206;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "CollideSkillID:" + CollideSkillID + ","
        + "BombSkillId:" + BombSkillId + ","
        + "Speed:" + Speed + ","
        + "LifeTime:" + LifeTime + ","
        + "collideCount:" + CollideCount + ","
        + "commonCD:" + CommonCD + ","
        + "ModelName:" + ModelName + ","
        + "ModelScale:" + ModelScale + ","
        + "ScriptName:" + ScriptName + ","
        + "ShootAudio:" + ShootAudio + ","
        + "ExplodeEffect:" + ExplodeEffect + ","
        + "HitEffect:" + HitEffect + ","
        + "}";
    }
}

}

