
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace Table
{
public partial class BulletCfgMgr
{
    private readonly System.Collections.Generic.Dictionary<int, BulletCfg> _dataMap;
    private readonly System.Collections.Generic.List<BulletCfg> _dataList;
    
    public BulletCfgMgr(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, BulletCfg>();
        _dataList = new System.Collections.Generic.List<BulletCfg>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            BulletCfg _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = BulletCfg.DeserializeBulletCfg(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, BulletCfg> DataMap => _dataMap;
    public System.Collections.Generic.List<BulletCfg> DataList => _dataList;

    public BulletCfg GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public BulletCfg Get(int key) => _dataMap[key];
    public BulletCfg this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

