
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace Table
{
public partial class DialogueCfgMgr
{
    private readonly System.Collections.Generic.Dictionary<int, DialogueCfg> _dataMap;
    private readonly System.Collections.Generic.List<DialogueCfg> _dataList;
    
    public DialogueCfgMgr(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, DialogueCfg>();
        _dataList = new System.Collections.Generic.List<DialogueCfg>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            DialogueCfg _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = DialogueCfg.DeserializeDialogueCfg(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Index, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, DialogueCfg> DataMap => _dataMap;
    public System.Collections.Generic.List<DialogueCfg> DataList => _dataList;

    public DialogueCfg GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public DialogueCfg Get(int key) => _dataMap[key];
    public DialogueCfg this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

