
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace Table
{
public sealed partial class DialogueCfg : Luban.BeanBase
{
    public DialogueCfg(JSONNode _buf) 
    {
        { if(!_buf["Index"].IsNumber) { throw new SerializationException(); }  Index = _buf["Index"]; }
        { if(!_buf["EventId"].IsNumber) { throw new SerializationException(); }  EventId = _buf["EventId"]; }
        { if(!_buf["ID"].IsNumber) { throw new SerializationException(); }  ID = _buf["ID"]; }
        { var __json0 = _buf["Goto"]; if(!__json0.IsArray) { throw new SerializationException(); } Goto = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  Goto.Add(__v0); }   }
        { if(!_buf["GotoPatam"].IsNumber) { throw new SerializationException(); }  GotoPatam = _buf["GotoPatam"]; }
        { var __json0 = _buf["Enemy"]; if(!__json0.IsArray) { throw new SerializationException(); } Enemy = new System.Collections.Generic.Dictionary<int, int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int _k0;  { if(!__e0[0].IsNumber) { throw new SerializationException(); }  _k0 = __e0[0]; } int _v0;  { if(!__e0[1].IsNumber) { throw new SerializationException(); }  _v0 = __e0[1]; }  Enemy.Add(_k0, _v0); }   }
        { var __json0 = _buf["Reward"]; if(!__json0.IsArray) { throw new SerializationException(); } Reward = new System.Collections.Generic.Dictionary<int, int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int _k0;  { if(!__e0[0].IsNumber) { throw new SerializationException(); }  _k0 = __e0[0]; } int _v0;  { if(!__e0[1].IsNumber) { throw new SerializationException(); }  _v0 = __e0[1]; }  Reward.Add(_k0, _v0); }   }
        { var __json0 = _buf["UnLockEventId"]; if(!__json0.IsArray) { throw new SerializationException(); } UnLockEventId = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  UnLockEventId.Add(__v0); }   }
        { if(!_buf["Title"].IsString) { throw new SerializationException(); }  Title = _buf["Title"]; }
        { if(!_buf["text"].IsString) { throw new SerializationException(); }  Text = _buf["text"]; }
    }

    public static DialogueCfg DeserializeDialogueCfg(JSONNode _buf)
    {
        return new DialogueCfg(_buf);
    }

    /// <summary>
    /// 唯一标记
    /// </summary>
    public readonly int Index;
    /// <summary>
    /// 所属事件ID
    /// </summary>
    public readonly int EventId;
    /// <summary>
    /// id
    /// </summary>
    public readonly int ID;
    /// <summary>
    /// 跳转
    /// </summary>
    public readonly System.Collections.Generic.List<int> Goto;
    /// <summary>
    /// 跳转参数
    /// </summary>
    public readonly int GotoPatam;
    /// <summary>
    /// 敌人
    /// </summary>
    public readonly System.Collections.Generic.Dictionary<int, int> Enemy;
    /// <summary>
    /// 掉落ID
    /// </summary>
    public readonly System.Collections.Generic.Dictionary<int, int> Reward;
    /// <summary>
    /// 解锁事件ID
    /// </summary>
    public readonly System.Collections.Generic.List<int> UnLockEventId;
    /// <summary>
    /// 标题
    /// </summary>
    public readonly string Title;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Text;
   
    public const int __ID__ = 1711433548;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Index:" + Index + ","
        + "EventId:" + EventId + ","
        + "ID:" + ID + ","
        + "Goto:" + Luban.StringUtil.CollectionToString(Goto) + ","
        + "GotoPatam:" + GotoPatam + ","
        + "Enemy:" + Luban.StringUtil.CollectionToString(Enemy) + ","
        + "Reward:" + Luban.StringUtil.CollectionToString(Reward) + ","
        + "UnLockEventId:" + Luban.StringUtil.CollectionToString(UnLockEventId) + ","
        + "Title:" + Title + ","
        + "text:" + Text + ","
        + "}";
    }
}

}

