
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace Table
{
public sealed partial class DropCfg : Luban.BeanBase
{
    public DropCfg(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["GroupId"].IsNumber) { throw new SerializationException(); }  GroupId = _buf["GroupId"]; }
        { if(!_buf["itemId"].IsNumber) { throw new SerializationException(); }  ItemId = _buf["itemId"]; }
        { if(!_buf["Weight"].IsNumber) { throw new SerializationException(); }  Weight = _buf["Weight"]; }
        { if(!_buf["MinNum"].IsNumber) { throw new SerializationException(); }  MinNum = _buf["MinNum"]; }
        { if(!_buf["MaxNum"].IsNumber) { throw new SerializationException(); }  MaxNum = _buf["MaxNum"]; }
    }

    public static DropCfg DeserializeDropCfg(JSONNode _buf)
    {
        return new DropCfg(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 组ID
    /// </summary>
    public readonly int GroupId;
    /// <summary>
    /// 道具ID
    /// </summary>
    public readonly int ItemId;
    /// <summary>
    /// 权重
    /// </summary>
    public readonly int Weight;
    /// <summary>
    /// 最小数量
    /// </summary>
    public readonly int MinNum;
    /// <summary>
    /// 最大数量
    /// </summary>
    public readonly int MaxNum;
   
    public const int __ID__ = -704620843;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "GroupId:" + GroupId + ","
        + "itemId:" + ItemId + ","
        + "Weight:" + Weight + ","
        + "MinNum:" + MinNum + ","
        + "MaxNum:" + MaxNum + ","
        + "}";
    }
}

}

