
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace Table
{
public partial class DropCfgMgr
{
    private readonly System.Collections.Generic.Dictionary<int, DropCfg> _dataMap;
    private readonly System.Collections.Generic.List<DropCfg> _dataList;
    
    public DropCfgMgr(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, DropCfg>();
        _dataList = new System.Collections.Generic.List<DropCfg>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            DropCfg _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = DropCfg.DeserializeDropCfg(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, DropCfg> DataMap => _dataMap;
    public System.Collections.Generic.List<DropCfg> DataList => _dataList;

    public DropCfg GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public DropCfg Get(int key) => _dataMap[key];
    public DropCfg this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

