
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace Table
{
public sealed partial class GlobalDefCfg : Luban.BeanBase
{
    public GlobalDefCfg(JSONNode _buf) 
    {
        { if(!_buf["id"].IsString) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["value"].IsString) { throw new SerializationException(); }  Value = _buf["value"]; }
    }

    public static GlobalDefCfg DeserializeGlobalDefCfg(JSONNode _buf)
    {
        return new GlobalDefCfg(_buf);
    }

    /// <summary>
    /// Key
    /// </summary>
    public readonly string Id;
    /// <summary>
    /// 值
    /// </summary>
    public readonly string Value;
   
    public const int __ID__ = -939128894;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "value:" + Value + ","
        + "}";
    }
}

}

