
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace Table
{
public sealed partial class HeroCfg : Luban.BeanBase
{
    public HeroCfg(JSONNode _buf) 
    {
        { if(!_buf["ID"].IsNumber) { throw new SerializationException(); }  ID = _buf["ID"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["Active"].IsBoolean) { throw new SerializationException(); }  Active = _buf["Active"]; }
        { var __json0 = _buf["skill"]; if(!__json0.IsArray) { throw new SerializationException(); } Skill = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  Skill.Add(__v0); }   }
        { if(!_buf["UnLock"].IsNumber) { throw new SerializationException(); }  UnLock = _buf["UnLock"]; }
        { if(!_buf["HP"].IsNumber) { throw new SerializationException(); }  HP = _buf["HP"]; }
        { if(!_buf["Speed"].IsNumber) { throw new SerializationException(); }  Speed = _buf["Speed"]; }
        { if(!_buf["Avatar"].IsString) { throw new SerializationException(); }  Avatar = _buf["Avatar"]; }
        { if(!_buf["UIAvatar"].IsString) { throw new SerializationException(); }  UIAvatar = _buf["UIAvatar"]; }
        { if(!_buf["Description"].IsString) { throw new SerializationException(); }  Description = _buf["Description"]; }
    }

    public static HeroCfg DeserializeHeroCfg(JSONNode _buf)
    {
        return new HeroCfg(_buf);
    }

    /// <summary>
    /// 职业ID
    /// </summary>
    public readonly int ID;
    /// <summary>
    /// 名字
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 激活
    /// </summary>
    public readonly bool Active;
    /// <summary>
    /// 技能
    /// </summary>
    public readonly System.Collections.Generic.List<int> Skill;
    /// <summary>
    /// 解锁消耗
    /// </summary>
    public readonly int UnLock;
    /// <summary>
    /// 血量
    /// </summary>
    public readonly int HP;
    /// <summary>
    /// 速度
    /// </summary>
    public readonly int Speed;
    /// <summary>
    /// 外观
    /// </summary>
    public readonly string Avatar;
    /// <summary>
    /// UI外观
    /// </summary>
    public readonly string UIAvatar;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Description;
   
    public const int __ID__ = -1819011606;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "name:" + Name + ","
        + "Active:" + Active + ","
        + "skill:" + Luban.StringUtil.CollectionToString(Skill) + ","
        + "UnLock:" + UnLock + ","
        + "HP:" + HP + ","
        + "Speed:" + Speed + ","
        + "Avatar:" + Avatar + ","
        + "UIAvatar:" + UIAvatar + ","
        + "Description:" + Description + ","
        + "}";
    }
}

}

