
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace Table
{
public partial class HeroCfgMgr
{
    private readonly System.Collections.Generic.Dictionary<int, HeroCfg> _dataMap;
    private readonly System.Collections.Generic.List<HeroCfg> _dataList;
    
    public HeroCfgMgr(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, HeroCfg>();
        _dataList = new System.Collections.Generic.List<HeroCfg>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            HeroCfg _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = HeroCfg.DeserializeHeroCfg(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, HeroCfg> DataMap => _dataMap;
    public System.Collections.Generic.List<HeroCfg> DataList => _dataList;

    public HeroCfg GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public HeroCfg Get(int key) => _dataMap[key];
    public HeroCfg this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

