
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace Table
{
public sealed partial class ItemBattleCfg : Luban.BeanBase
{
    public ItemBattleCfg(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["quality"].IsNumber) { throw new SerializationException(); }  Quality = _buf["quality"]; }
        { if(!_buf["ItemType"].IsNumber) { throw new SerializationException(); }  ItemType = _buf["ItemType"]; }
        { if(!_buf["Value1"].IsNumber) { throw new SerializationException(); }  Value1 = _buf["Value1"]; }
        { if(!_buf["Value2"].IsNumber) { throw new SerializationException(); }  Value2 = _buf["Value2"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["prefab"].IsString) { throw new SerializationException(); }  Prefab = _buf["prefab"]; }
        { if(!_buf["icon"].IsString) { throw new SerializationException(); }  Icon = _buf["icon"]; }
        { if(!_buf["desc"].IsString) { throw new SerializationException(); }  Desc = _buf["desc"]; }
    }

    public static ItemBattleCfg DeserializeItemBattleCfg(JSONNode _buf)
    {
        return new ItemBattleCfg(_buf);
    }

    /// <summary>
    /// 这是id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 品质
    /// </summary>
    public readonly int Quality;
    /// <summary>
    /// 道具类型
    /// </summary>
    public readonly int ItemType;
    /// <summary>
    /// 参数
    /// </summary>
    public readonly int Value1;
    /// <summary>
    /// 参数2
    /// </summary>
    public readonly int Value2;
    /// <summary>
    /// 名字
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 游戏Obj
    /// </summary>
    public readonly string Prefab;
    /// <summary>
    /// 图标
    /// </summary>
    public readonly string Icon;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;
   
    public const int __ID__ = -1682442599;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "quality:" + Quality + ","
        + "ItemType:" + ItemType + ","
        + "Value1:" + Value1 + ","
        + "Value2:" + Value2 + ","
        + "name:" + Name + ","
        + "prefab:" + Prefab + ","
        + "icon:" + Icon + ","
        + "desc:" + Desc + ","
        + "}";
    }
}

}

