
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace Table
{
public partial class ItemBattleCfgMgr
{
    private readonly System.Collections.Generic.Dictionary<int, ItemBattleCfg> _dataMap;
    private readonly System.Collections.Generic.List<ItemBattleCfg> _dataList;
    
    public ItemBattleCfgMgr(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, ItemBattleCfg>();
        _dataList = new System.Collections.Generic.List<ItemBattleCfg>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            ItemBattleCfg _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = ItemBattleCfg.DeserializeItemBattleCfg(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, ItemBattleCfg> DataMap => _dataMap;
    public System.Collections.Generic.List<ItemBattleCfg> DataList => _dataList;

    public ItemBattleCfg GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public ItemBattleCfg Get(int key) => _dataMap[key];
    public ItemBattleCfg this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

