
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace Table
{
public sealed partial class ItemCfg : Luban.BeanBase
{
    public ItemCfg(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["quality"].IsNumber) { throw new SerializationException(); }  Quality = _buf["quality"]; }
        { if(!_buf["ItemType"].IsNumber) { throw new SerializationException(); }  ItemType = _buf["ItemType"]; }
        { if(!_buf["SubType"].IsNumber) { throw new SerializationException(); }  SubType = _buf["SubType"]; }
        { if(!_buf["Str"].IsNumber) { throw new SerializationException(); }  Str = _buf["Str"]; }
        { if(!_buf["Int"].IsNumber) { throw new SerializationException(); }  Int = _buf["Int"]; }
        { if(!_buf["Agi"].IsNumber) { throw new SerializationException(); }  Agi = _buf["Agi"]; }
        { if(!_buf["Phy"].IsNumber) { throw new SerializationException(); }  Phy = _buf["Phy"]; }
        { if(!_buf["Spi"].IsNumber) { throw new SerializationException(); }  Spi = _buf["Spi"]; }
        { if(!_buf["Luck"].IsNumber) { throw new SerializationException(); }  Luck = _buf["Luck"]; }
        { if(!_buf["skillId"].IsNumber) { throw new SerializationException(); }  SkillId = _buf["skillId"]; }
        { if(!_buf["icon"].IsString) { throw new SerializationException(); }  Icon = _buf["icon"]; }
        { if(!_buf["prefab"].IsString) { throw new SerializationException(); }  Prefab = _buf["prefab"]; }
        { if(!_buf["desc"].IsString) { throw new SerializationException(); }  Desc = _buf["desc"]; }
    }

    public static ItemCfg DeserializeItemCfg(JSONNode _buf)
    {
        return new ItemCfg(_buf);
    }

    /// <summary>
    /// 这是id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名字
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 品质
    /// </summary>
    public readonly int Quality;
    /// <summary>
    /// 道具类型
    /// </summary>
    public readonly int ItemType;
    /// <summary>
    /// 子类型
    /// </summary>
    public readonly int SubType;
    /// <summary>
    /// 力
    /// </summary>
    public readonly int Str;
    /// <summary>
    /// 智
    /// </summary>
    public readonly int Int;
    /// <summary>
    /// 敏
    /// </summary>
    public readonly int Agi;
    /// <summary>
    /// 体
    /// </summary>
    public readonly int Phy;
    /// <summary>
    /// 精
    /// </summary>
    public readonly int Spi;
    /// <summary>
    /// 幸
    /// </summary>
    public readonly int Luck;
    /// <summary>
    /// 技能
    /// </summary>
    public readonly int SkillId;
    /// <summary>
    /// 图标
    /// </summary>
    public readonly string Icon;
    /// <summary>
    /// 游戏Obj
    /// </summary>
    public readonly string Prefab;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;
   
    public const int __ID__ = -514136015;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "quality:" + Quality + ","
        + "ItemType:" + ItemType + ","
        + "SubType:" + SubType + ","
        + "Str:" + Str + ","
        + "Int:" + Int + ","
        + "Agi:" + Agi + ","
        + "Phy:" + Phy + ","
        + "Spi:" + Spi + ","
        + "Luck:" + Luck + ","
        + "skillId:" + SkillId + ","
        + "icon:" + Icon + ","
        + "prefab:" + Prefab + ","
        + "desc:" + Desc + ","
        + "}";
    }
}

}

