
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace Table
{
public sealed partial class MapCfg : Luban.BeanBase
{
    public MapCfg(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["MapName"].IsString) { throw new SerializationException(); }  MapName = _buf["MapName"]; }
        { if(!_buf["MapScene"].IsString) { throw new SerializationException(); }  MapScene = _buf["MapScene"]; }
        { if(!_buf["Script"].IsString) { throw new SerializationException(); }  Script = _buf["Script"]; }
        { if(!_buf["Icon"].IsString) { throw new SerializationException(); }  Icon = _buf["Icon"]; }
        { if(!_buf["MapDescribe"].IsString) { throw new SerializationException(); }  MapDescribe = _buf["MapDescribe"]; }
    }

    public static MapCfg DeserializeMapCfg(JSONNode _buf)
    {
        return new MapCfg(_buf);
    }

    /// <summary>
    /// 地图ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 地图名字
    /// </summary>
    public readonly string MapName;
    /// <summary>
    /// 地图场景
    /// </summary>
    public readonly string MapScene;
    /// <summary>
    /// 地图脚本
    /// </summary>
    public readonly string Script;
    /// <summary>
    /// 图标
    /// </summary>
    public readonly string Icon;
    /// <summary>
    /// 地图描述
    /// </summary>
    public readonly string MapDescribe;
   
    public const int __ID__ = -1997536888;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "MapName:" + MapName + ","
        + "MapScene:" + MapScene + ","
        + "Script:" + Script + ","
        + "Icon:" + Icon + ","
        + "MapDescribe:" + MapDescribe + ","
        + "}";
    }
}

}

