
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace Table
{
public sealed partial class MapRankCfg : Luban.BeanBase
{
    public MapRankCfg(JSONNode _buf) 
    {
        { if(!_buf["Index"].IsNumber) { throw new SerializationException(); }  Index = _buf["Index"]; }
        { if(!_buf["MapId"].IsNumber) { throw new SerializationException(); }  MapId = _buf["MapId"]; }
        { if(!_buf["Rank"].IsNumber) { throw new SerializationException(); }  Rank = _buf["Rank"]; }
        { if(!_buf["Condition"].IsNumber) { throw new SerializationException(); }  Condition = _buf["Condition"]; }
        { if(!_buf["Name"].IsString) { throw new SerializationException(); }  Name = _buf["Name"]; }
        { if(!_buf["WaveGroup"].IsNumber) { throw new SerializationException(); }  WaveGroup = _buf["WaveGroup"]; }
        { if(!_buf["HPAdd"].IsNumber) { throw new SerializationException(); }  HPAdd = _buf["HPAdd"]; }
        { if(!_buf["SpeedAdd"].IsNumber) { throw new SerializationException(); }  SpeedAdd = _buf["SpeedAdd"]; }
        { if(!_buf["BodyAdd"].IsNumber) { throw new SerializationException(); }  BodyAdd = _buf["BodyAdd"]; }
        { if(!_buf["Describe"].IsString) { throw new SerializationException(); }  Describe = _buf["Describe"]; }
    }

    public static MapRankCfg DeserializeMapRankCfg(JSONNode _buf)
    {
        return new MapRankCfg(_buf);
    }

    /// <summary>
    /// index
    /// </summary>
    public readonly int Index;
    /// <summary>
    /// 地图ID
    /// </summary>
    public readonly int MapId;
    /// <summary>
    /// 等级
    /// </summary>
    public readonly int Rank;
    /// <summary>
    /// 解锁条件
    /// </summary>
    public readonly int Condition;
    /// <summary>
    /// 难度名字
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 怪物波次组
    /// </summary>
    public readonly int WaveGroup;
    /// <summary>
    /// HP增幅
    /// </summary>
    public readonly float HPAdd;
    /// <summary>
    /// 速度增幅
    /// </summary>
    public readonly float SpeedAdd;
    /// <summary>
    /// 体型增幅
    /// </summary>
    public readonly float BodyAdd;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Describe;
   
    public const int __ID__ = -1207071812;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Index:" + Index + ","
        + "MapId:" + MapId + ","
        + "Rank:" + Rank + ","
        + "Condition:" + Condition + ","
        + "Name:" + Name + ","
        + "WaveGroup:" + WaveGroup + ","
        + "HPAdd:" + HPAdd + ","
        + "SpeedAdd:" + SpeedAdd + ","
        + "BodyAdd:" + BodyAdd + ","
        + "Describe:" + Describe + ","
        + "}";
    }
}

}

