
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace Table
{
public partial class MapRankCfgMgr
{
    private readonly System.Collections.Generic.Dictionary<int, MapRankCfg> _dataMap;
    private readonly System.Collections.Generic.List<MapRankCfg> _dataList;
    
    public MapRankCfgMgr(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, MapRankCfg>();
        _dataList = new System.Collections.Generic.List<MapRankCfg>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            MapRankCfg _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = MapRankCfg.DeserializeMapRankCfg(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Index, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, MapRankCfg> DataMap => _dataMap;
    public System.Collections.Generic.List<MapRankCfg> DataList => _dataList;

    public MapRankCfg GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public MapRankCfg Get(int key) => _dataMap[key];
    public MapRankCfg this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

