
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace Table
{
public partial class MonsterCfgMgr
{
    private readonly System.Collections.Generic.Dictionary<int, MonsterCfg> _dataMap;
    private readonly System.Collections.Generic.List<MonsterCfg> _dataList;
    
    public MonsterCfgMgr(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, MonsterCfg>();
        _dataList = new System.Collections.Generic.List<MonsterCfg>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            MonsterCfg _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = MonsterCfg.DeserializeMonsterCfg(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, MonsterCfg> DataMap => _dataMap;
    public System.Collections.Generic.List<MonsterCfg> DataList => _dataList;

    public MonsterCfg GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public MonsterCfg Get(int key) => _dataMap[key];
    public MonsterCfg this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

