
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace Table
{
public sealed partial class MonsterCfg : Luban.BeanBase
{
    public MonsterCfg(JSONNode _buf) 
    {
        { if(!_buf["ID"].IsNumber) { throw new SerializationException(); }  ID = _buf["ID"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["AITreeType"].IsNumber) { throw new SerializationException(); }  AITreeType = _buf["AITreeType"]; }
        { if(!_buf["Rank"].IsNumber) { throw new SerializationException(); }  Rank = _buf["Rank"]; }
        { if(!_buf["HP"].IsNumber) { throw new SerializationException(); }  HP = _buf["HP"]; }
        { if(!_buf["LifeTime"].IsNumber) { throw new SerializationException(); }  LifeTime = _buf["LifeTime"]; }
        { if(!_buf["Speed"].IsNumber) { throw new SerializationException(); }  Speed = _buf["Speed"]; }
        { if(!_buf["RepelRe"].IsNumber) { throw new SerializationException(); }  RepelRe = _buf["RepelRe"]; }
        { if(!_buf["BodySize"].IsNumber) { throw new SerializationException(); }  BodySize = _buf["BodySize"]; }
        { if(!_buf["RVOLayer"].IsNumber) { throw new SerializationException(); }  RVOLayer = _buf["RVOLayer"]; }
        { var __json0 = _buf["SkillList"]; if(!__json0.IsArray) { throw new SerializationException(); } SkillList = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  SkillList.Add(__v0); }   }
        { if(!_buf["DropID"].IsNumber) { throw new SerializationException(); }  DropID = _buf["DropID"]; }
        { if(!_buf["DeadSkillId"].IsNumber) { throw new SerializationException(); }  DeadSkillId = _buf["DeadSkillId"]; }
        { if(!_buf["Prefab"].IsString) { throw new SerializationException(); }  Prefab = _buf["Prefab"]; }
        { if(!_buf["DeadAudio"].IsString) { throw new SerializationException(); }  DeadAudio = _buf["DeadAudio"]; }
        { if(!_buf["DeadEffect"].IsString) { throw new SerializationException(); }  DeadEffect = _buf["DeadEffect"]; }
        { if(!_buf["Describe"].IsString) { throw new SerializationException(); }  Describe = _buf["Describe"]; }
    }

    public static MonsterCfg DeserializeMonsterCfg(JSONNode _buf)
    {
        return new MonsterCfg(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int ID;
    /// <summary>
    /// 名字
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// AI树类型
    /// </summary>
    public readonly int AITreeType;
    /// <summary>
    /// 评级
    /// </summary>
    public readonly int Rank;
    /// <summary>
    /// 血量
    /// </summary>
    public readonly int HP;
    /// <summary>
    /// 生存时间
    /// </summary>
    public readonly float LifeTime;
    /// <summary>
    /// 速度
    /// </summary>
    public readonly float Speed;
    /// <summary>
    /// 击退抗性
    /// </summary>
    public readonly float RepelRe;
    /// <summary>
    /// 尺寸
    /// </summary>
    public readonly float BodySize;
    /// <summary>
    /// 碰撞层级
    /// </summary>
    public readonly int RVOLayer;
    /// <summary>
    /// 技能列表
    /// </summary>
    public readonly System.Collections.Generic.List<int> SkillList;
    /// <summary>
    /// 掉落
    /// </summary>
    public readonly int DropID;
    /// <summary>
    /// 死亡技能
    /// </summary>
    public readonly int DeadSkillId;
    /// <summary>
    /// 模型路径
    /// </summary>
    public readonly string Prefab;
    /// <summary>
    /// 死亡音效
    /// </summary>
    public readonly string DeadAudio;
    /// <summary>
    /// 死亡特效(血迹)
    /// </summary>
    public readonly string DeadEffect;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Describe;
   
    public const int __ID__ = -173582774;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "name:" + Name + ","
        + "AITreeType:" + AITreeType + ","
        + "Rank:" + Rank + ","
        + "HP:" + HP + ","
        + "LifeTime:" + LifeTime + ","
        + "Speed:" + Speed + ","
        + "RepelRe:" + RepelRe + ","
        + "BodySize:" + BodySize + ","
        + "RVOLayer:" + RVOLayer + ","
        + "SkillList:" + Luban.StringUtil.CollectionToString(SkillList) + ","
        + "DropID:" + DropID + ","
        + "DeadSkillId:" + DeadSkillId + ","
        + "Prefab:" + Prefab + ","
        + "DeadAudio:" + DeadAudio + ","
        + "DeadEffect:" + DeadEffect + ","
        + "Describe:" + Describe + ","
        + "}";
    }
}

}

