
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace Table
{
public sealed partial class PrefabsEffectCfg : Luban.BeanBase
{
    public PrefabsEffectCfg(JSONNode _buf) 
    {
        { if(!_buf["EffectName"].IsString) { throw new SerializationException(); }  EffectName = _buf["EffectName"]; }
        { if(!_buf["EffectPath"].IsString) { throw new SerializationException(); }  EffectPath = _buf["EffectPath"]; }
        { if(!_buf["IsRotateForMaster"].IsBoolean) { throw new SerializationException(); }  IsRotateForMaster = _buf["IsRotateForMaster"]; }
        { if(!_buf["Describe"].IsString) { throw new SerializationException(); }  Describe = _buf["Describe"]; }
        { if(!_buf["preLoadCount"].IsNumber) { throw new SerializationException(); }  PreLoadCount = _buf["preLoadCount"]; }
    }

    public static PrefabsEffectCfg DeserializePrefabsEffectCfg(JSONNode _buf)
    {
        return new PrefabsEffectCfg(_buf);
    }

    /// <summary>
    /// 特效名字
    /// </summary>
    public readonly string EffectName;
    /// <summary>
    /// 资源路径
    /// </summary>
    public readonly string EffectPath;
    /// <summary>
    /// 是否跟随宿主旋转
    /// </summary>
    public readonly bool IsRotateForMaster;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Describe;
    /// <summary>
    /// 预加载数量
    /// </summary>
    public readonly int PreLoadCount;
   
    public const int __ID__ = 1824615044;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "EffectName:" + EffectName + ","
        + "EffectPath:" + EffectPath + ","
        + "IsRotateForMaster:" + IsRotateForMaster + ","
        + "Describe:" + Describe + ","
        + "preLoadCount:" + PreLoadCount + ","
        + "}";
    }
}

}

