
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace Table
{
public partial class PrefabsEffectCfgMgr
{
    private readonly System.Collections.Generic.Dictionary<string, PrefabsEffectCfg> _dataMap;
    private readonly System.Collections.Generic.List<PrefabsEffectCfg> _dataList;
    
    public PrefabsEffectCfgMgr(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<string, PrefabsEffectCfg>();
        _dataList = new System.Collections.Generic.List<PrefabsEffectCfg>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            PrefabsEffectCfg _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = PrefabsEffectCfg.DeserializePrefabsEffectCfg(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.EffectName, _v);
        }
    }

    public System.Collections.Generic.Dictionary<string, PrefabsEffectCfg> DataMap => _dataMap;
    public System.Collections.Generic.List<PrefabsEffectCfg> DataList => _dataList;

    public PrefabsEffectCfg GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public PrefabsEffectCfg Get(string key) => _dataMap[key];
    public PrefabsEffectCfg this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

