
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace Table
{
public sealed partial class ProfebsModelCfg : Luban.BeanBase
{
    public ProfebsModelCfg(JSONNode _buf) 
    {
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["path"].IsString) { throw new SerializationException(); }  Path = _buf["path"]; }
        { if(!_buf["Describe"].IsString) { throw new SerializationException(); }  Describe = _buf["Describe"]; }
        { if(!_buf["profebType"].IsNumber) { throw new SerializationException(); }  ProfebType = _buf["profebType"]; }
        { if(!_buf["preLoadCount"].IsNumber) { throw new SerializationException(); }  PreLoadCount = _buf["preLoadCount"]; }
    }

    public static ProfebsModelCfg DeserializeProfebsModelCfg(JSONNode _buf)
    {
        return new ProfebsModelCfg(_buf);
    }

    /// <summary>
    /// 名字
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 资源路径
    /// </summary>
    public readonly string Path;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Describe;
    /// <summary>
    /// 资源类型
    /// </summary>
    public readonly int ProfebType;
    /// <summary>
    /// 预加载数量
    /// </summary>
    public readonly int PreLoadCount;
   
    public const int __ID__ = -520709896;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "name:" + Name + ","
        + "path:" + Path + ","
        + "Describe:" + Describe + ","
        + "profebType:" + ProfebType + ","
        + "preLoadCount:" + PreLoadCount + ","
        + "}";
    }
}

}

