
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace Table
{
public partial class ProfebsModelCfgMgr
{
    private readonly System.Collections.Generic.Dictionary<string, ProfebsModelCfg> _dataMap;
    private readonly System.Collections.Generic.List<ProfebsModelCfg> _dataList;
    
    public ProfebsModelCfgMgr(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<string, ProfebsModelCfg>();
        _dataList = new System.Collections.Generic.List<ProfebsModelCfg>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            ProfebsModelCfg _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = ProfebsModelCfg.DeserializeProfebsModelCfg(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Name, _v);
        }
    }

    public System.Collections.Generic.Dictionary<string, ProfebsModelCfg> DataMap => _dataMap;
    public System.Collections.Generic.List<ProfebsModelCfg> DataList => _dataList;

    public ProfebsModelCfg GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public ProfebsModelCfg Get(string key) => _dataMap[key];
    public ProfebsModelCfg this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

