
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace Table
{
public sealed partial class SkillLvCfg : Luban.BeanBase
{
    public SkillLvCfg(JSONNode _buf) 
    {
        { if(!_buf["index"].IsNumber) { throw new SerializationException(); }  Index = _buf["index"]; }
        { if(!_buf["skillId"].IsNumber) { throw new SerializationException(); }  SkillId = _buf["skillId"]; }
        { if(!_buf["level"].IsNumber) { throw new SerializationException(); }  Level = _buf["level"]; }
        { if(!_buf["Describe"].IsString) { throw new SerializationException(); }  Describe = _buf["Describe"]; }
        { if(!_buf["CD"].IsNumber) { throw new SerializationException(); }  CD = _buf["CD"]; }
        { if(!_buf["CastRange"].IsNumber) { throw new SerializationException(); }  CastRange = _buf["CastRange"]; }
        { if(!_buf["SearchWay"].IsNumber) { throw new SerializationException(); }  SearchWay = _buf["SearchWay"]; }
        { if(!_buf["HitRange"].IsNumber) { throw new SerializationException(); }  HitRange = _buf["HitRange"]; }
        { if(!_buf["Angle"].IsNumber) { throw new SerializationException(); }  Angle = _buf["Angle"]; }
        { if(!_buf["MaxTar"].IsNumber) { throw new SerializationException(); }  MaxTar = _buf["MaxTar"]; }
        { if(!_buf["Damage"].IsNumber) { throw new SerializationException(); }  Damage = _buf["Damage"]; }
        { if(!_buf["BulletID"].IsNumber) { throw new SerializationException(); }  BulletID = _buf["BulletID"]; }
        { if(!_buf["ShotNum"].IsNumber) { throw new SerializationException(); }  ShotNum = _buf["ShotNum"]; }
        { if(!_buf["ShootType"].IsNumber) { throw new SerializationException(); }  ShootType = _buf["ShootType"]; }
        { var __json0 = _buf["Status"]; if(!__json0.IsArray) { throw new SerializationException(); } Status = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  Status.Add(__v0); }   }
        { var __json0 = _buf["PassiveStatus"]; if(!__json0.IsArray) { throw new SerializationException(); } PassiveStatus = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  PassiveStatus.Add(__v0); }   }
    }

    public static SkillLvCfg DeserializeSkillLvCfg(JSONNode _buf)
    {
        return new SkillLvCfg(_buf);
    }

    /// <summary>
    /// index
    /// </summary>
    public readonly int Index;
    /// <summary>
    /// 技能ID
    /// </summary>
    public readonly int SkillId;
    /// <summary>
    /// 技能等级
    /// </summary>
    public readonly int Level;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Describe;
    /// <summary>
    /// 冷却
    /// </summary>
    public readonly float CD;
    /// <summary>
    /// 施法范围
    /// </summary>
    public readonly float CastRange;
    /// <summary>
    /// 选取方式
    /// </summary>
    public readonly int SearchWay;
    /// <summary>
    /// 选取范围
    /// </summary>
    public readonly float HitRange;
    /// <summary>
    /// 选取角度
    /// </summary>
    public readonly float Angle;
    /// <summary>
    /// 最大目标数
    /// </summary>
    public readonly int MaxTar;
    /// <summary>
    /// 伤害
    /// </summary>
    public readonly int Damage;
    /// <summary>
    /// 子弹ID
    /// </summary>
    public readonly int BulletID;
    /// <summary>
    /// 发射数量
    /// </summary>
    public readonly int ShotNum;
    /// <summary>
    /// 发射方式
    /// </summary>
    public readonly int ShootType;
    /// <summary>
    /// 附加状态
    /// </summary>
    public readonly System.Collections.Generic.List<int> Status;
    /// <summary>
    /// 被动状态
    /// </summary>
    public readonly System.Collections.Generic.List<int> PassiveStatus;
   
    public const int __ID__ = -711490871;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "index:" + Index + ","
        + "skillId:" + SkillId + ","
        + "level:" + Level + ","
        + "Describe:" + Describe + ","
        + "CD:" + CD + ","
        + "CastRange:" + CastRange + ","
        + "SearchWay:" + SearchWay + ","
        + "HitRange:" + HitRange + ","
        + "Angle:" + Angle + ","
        + "MaxTar:" + MaxTar + ","
        + "Damage:" + Damage + ","
        + "BulletID:" + BulletID + ","
        + "ShotNum:" + ShotNum + ","
        + "ShootType:" + ShootType + ","
        + "Status:" + Luban.StringUtil.CollectionToString(Status) + ","
        + "PassiveStatus:" + Luban.StringUtil.CollectionToString(PassiveStatus) + ","
        + "}";
    }
}

}

