
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace Table
{
public partial class SkillCfgMgr
{
    private readonly System.Collections.Generic.Dictionary<int, SkillCfg> _dataMap;
    private readonly System.Collections.Generic.List<SkillCfg> _dataList;
    
    public SkillCfgMgr(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, SkillCfg>();
        _dataList = new System.Collections.Generic.List<SkillCfg>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            SkillCfg _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = SkillCfg.DeserializeSkillCfg(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, SkillCfg> DataMap => _dataMap;
    public System.Collections.Generic.List<SkillCfg> DataList => _dataList;

    public SkillCfg GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public SkillCfg Get(int key) => _dataMap[key];
    public SkillCfg this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

