
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace Table
{
public sealed partial class SkillCfg : Luban.BeanBase
{
    public SkillCfg(JSONNode _buf) 
    {
        { if(!_buf["ID"].IsNumber) { throw new SerializationException(); }  ID = _buf["ID"]; }
        { if(!_buf["ShowName"].IsString) { throw new SerializationException(); }  ShowName = _buf["ShowName"]; }
        { if(!_buf["MasterSkill"].IsNumber) { throw new SerializationException(); }  MasterSkill = _buf["MasterSkill"]; }
        { if(!_buf["ScriptName"].IsString) { throw new SerializationException(); }  ScriptName = _buf["ScriptName"]; }
        { if(!_buf["FreeCast"].IsBoolean) { throw new SerializationException(); }  FreeCast = _buf["FreeCast"]; }
        { if(!_buf["TargetType"].IsNumber) { throw new SerializationException(); }  TargetType = _buf["TargetType"]; }
        { if(!_buf["SkillType"].IsNumber) { throw new SerializationException(); }  SkillType = _buf["SkillType"]; }
        { if(!_buf["CastType"].IsNumber) { throw new SerializationException(); }  CastType = _buf["CastType"]; }
        { if(!_buf["StartTime"].IsNumber) { throw new SerializationException(); }  StartTime = _buf["StartTime"]; }
        { if(!_buf["FinishTime"].IsNumber) { throw new SerializationException(); }  FinishTime = _buf["FinishTime"]; }
        { if(!_buf["Icon"].IsString) { throw new SerializationException(); }  Icon = _buf["Icon"]; }
        { if(!_buf["ShotEffect"].IsString) { throw new SerializationException(); }  ShotEffect = _buf["ShotEffect"]; }
        { if(!_buf["HitEffect"].IsString) { throw new SerializationException(); }  HitEffect = _buf["HitEffect"]; }
        { if(!_buf["ShotAudio"].IsString) { throw new SerializationException(); }  ShotAudio = _buf["ShotAudio"]; }
        { if(!_buf["HitAudio"].IsString) { throw new SerializationException(); }  HitAudio = _buf["HitAudio"]; }
    }

    public static SkillCfg DeserializeSkillCfg(JSONNode _buf)
    {
        return new SkillCfg(_buf);
    }

    /// <summary>
    /// skillID
    /// </summary>
    public readonly int ID;
    /// <summary>
    /// 显示名称
    /// </summary>
    public readonly string ShowName;
    /// <summary>
    /// 归属技能
    /// </summary>
    public readonly int MasterSkill;
    /// <summary>
    /// 脚本
    /// </summary>
    public readonly string ScriptName;
    /// <summary>
    /// 自由释放
    /// </summary>
    public readonly bool FreeCast;
    /// <summary>
    /// 目标类型
    /// </summary>
    public readonly int TargetType;
    /// <summary>
    /// 技能类型
    /// </summary>
    public readonly int SkillType;
    /// <summary>
    /// 施法类型
    /// </summary>
    public readonly int CastType;
    /// <summary>
    /// 前摇时间
    /// </summary>
    public readonly float StartTime;
    /// <summary>
    /// 后摇时间
    /// </summary>
    public readonly float FinishTime;
    /// <summary>
    /// 图标
    /// </summary>
    public readonly string Icon;
    /// <summary>
    /// 出手特效
    /// </summary>
    public readonly string ShotEffect;
    /// <summary>
    /// 受击特效
    /// </summary>
    public readonly string HitEffect;
    /// <summary>
    /// 出手音效
    /// </summary>
    public readonly string ShotAudio;
    /// <summary>
    /// 命中音效
    /// </summary>
    public readonly string HitAudio;
   
    public const int __ID__ = -2087897997;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "ShowName:" + ShowName + ","
        + "MasterSkill:" + MasterSkill + ","
        + "ScriptName:" + ScriptName + ","
        + "FreeCast:" + FreeCast + ","
        + "TargetType:" + TargetType + ","
        + "SkillType:" + SkillType + ","
        + "CastType:" + CastType + ","
        + "StartTime:" + StartTime + ","
        + "FinishTime:" + FinishTime + ","
        + "Icon:" + Icon + ","
        + "ShotEffect:" + ShotEffect + ","
        + "HitEffect:" + HitEffect + ","
        + "ShotAudio:" + ShotAudio + ","
        + "HitAudio:" + HitAudio + ","
        + "}";
    }
}

}

