
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace Table
{
public partial class SkillLvCfgMgr
{
    private readonly System.Collections.Generic.Dictionary<int, SkillLvCfg> _dataMap;
    private readonly System.Collections.Generic.List<SkillLvCfg> _dataList;
    
    public SkillLvCfgMgr(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, SkillLvCfg>();
        _dataList = new System.Collections.Generic.List<SkillLvCfg>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            SkillLvCfg _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = SkillLvCfg.DeserializeSkillLvCfg(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Index, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, SkillLvCfg> DataMap => _dataMap;
    public System.Collections.Generic.List<SkillLvCfg> DataList => _dataList;

    public SkillLvCfg GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public SkillLvCfg Get(int key) => _dataMap[key];
    public SkillLvCfg this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

