
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace Table
{
public partial class StatusCfgMgr
{
    private readonly System.Collections.Generic.Dictionary<int, StatusCfg> _dataMap;
    private readonly System.Collections.Generic.List<StatusCfg> _dataList;
    
    public StatusCfgMgr(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, StatusCfg>();
        _dataList = new System.Collections.Generic.List<StatusCfg>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            StatusCfg _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = StatusCfg.DeserializeStatusCfg(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, StatusCfg> DataMap => _dataMap;
    public System.Collections.Generic.List<StatusCfg> DataList => _dataList;

    public StatusCfg GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public StatusCfg Get(int key) => _dataMap[key];
    public StatusCfg this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

