
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace Table
{
public sealed partial class StatusCfg : Luban.BeanBase
{
    public StatusCfg(JSONNode _buf) 
    {
        { if(!_buf["ID"].IsNumber) { throw new SerializationException(); }  ID = _buf["ID"]; }
        { if(!_buf["Level"].IsNumber) { throw new SerializationException(); }  Level = _buf["Level"]; }
        { if(!_buf["Name"].IsString) { throw new SerializationException(); }  Name = _buf["Name"]; }
        { if(!_buf["Script"].IsString) { throw new SerializationException(); }  Script = _buf["Script"]; }
        { if(!_buf["Discribe"].IsString) { throw new SerializationException(); }  Discribe = _buf["Discribe"]; }
        { if(!_buf["StepTime"].IsNumber) { throw new SerializationException(); }  StepTime = _buf["StepTime"]; }
        { if(!_buf["Duration"].IsNumber) { throw new SerializationException(); }  Duration = _buf["Duration"]; }
        { if(!_buf["MaxLayer"].IsNumber) { throw new SerializationException(); }  MaxLayer = _buf["MaxLayer"]; }
        { if(!_buf["overlayType"].IsNumber) { throw new SerializationException(); }  OverlayType = _buf["overlayType"]; }
        { if(!_buf["BulletCount"].IsNumber) { throw new SerializationException(); }  BulletCount = _buf["BulletCount"]; }
        { if(!_buf["ShotNum"].IsNumber) { throw new SerializationException(); }  ShotNum = _buf["ShotNum"]; }
        { if(!_buf["ReloadTime"].IsNumber) { throw new SerializationException(); }  ReloadTime = _buf["ReloadTime"]; }
        { if(!_buf["ShotSpeed"].IsNumber) { throw new SerializationException(); }  ShotSpeed = _buf["ShotSpeed"]; }
        { if(!_buf["BulletSpeed"].IsNumber) { throw new SerializationException(); }  BulletSpeed = _buf["BulletSpeed"]; }
        { if(!_buf["WeaponRange"].IsNumber) { throw new SerializationException(); }  WeaponRange = _buf["WeaponRange"]; }
        { if(!_buf["State"].IsNumber) { throw new SerializationException(); }  State = _buf["State"]; }
        { if(!_buf["Effect"].IsString) { throw new SerializationException(); }  Effect = _buf["Effect"]; }
        { if(!_buf["Icon"].IsString) { throw new SerializationException(); }  Icon = _buf["Icon"]; }
    }

    public static StatusCfg DeserializeStatusCfg(JSONNode _buf)
    {
        return new StatusCfg(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int ID;
    /// <summary>
    /// 等级
    /// </summary>
    public readonly int Level;
    /// <summary>
    /// 名字
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 脚本名
    /// </summary>
    public readonly string Script;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Discribe;
    /// <summary>
    /// 触发间隔
    /// </summary>
    public readonly int StepTime;
    /// <summary>
    /// 持续时间
    /// </summary>
    public readonly int Duration;
    /// <summary>
    /// 叠加层数
    /// </summary>
    public readonly int MaxLayer;
    /// <summary>
    /// 叠加类型
    /// </summary>
    public readonly int OverlayType;
    /// <summary>
    /// 子弹个数
    /// </summary>
    public readonly int BulletCount;
    /// <summary>
    /// 发射数量
    /// </summary>
    public readonly int ShotNum;
    /// <summary>
    /// 加载时间
    /// </summary>
    public readonly float ReloadTime;
    /// <summary>
    /// 发射速度
    /// </summary>
    public readonly float ShotSpeed;
    /// <summary>
    /// 子弹速度
    /// </summary>
    public readonly float BulletSpeed;
    /// <summary>
    /// 武器射程
    /// </summary>
    public readonly float WeaponRange;
    /// <summary>
    /// State
    /// </summary>
    public readonly int State;
    /// <summary>
    /// 附着特效
    /// </summary>
    public readonly string Effect;
    /// <summary>
    /// 图标
    /// </summary>
    public readonly string Icon;
   
    public const int __ID__ = -66258190;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "Level:" + Level + ","
        + "Name:" + Name + ","
        + "Script:" + Script + ","
        + "Discribe:" + Discribe + ","
        + "StepTime:" + StepTime + ","
        + "Duration:" + Duration + ","
        + "MaxLayer:" + MaxLayer + ","
        + "overlayType:" + OverlayType + ","
        + "BulletCount:" + BulletCount + ","
        + "ShotNum:" + ShotNum + ","
        + "ReloadTime:" + ReloadTime + ","
        + "ShotSpeed:" + ShotSpeed + ","
        + "BulletSpeed:" + BulletSpeed + ","
        + "WeaponRange:" + WeaponRange + ","
        + "State:" + State + ","
        + "Effect:" + Effect + ","
        + "Icon:" + Icon + ","
        + "}";
    }
}

}

