
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;

namespace Table
{
public partial class Tables
{
    public ItemCfgMgr ItemCfgMgr {get; }
    public ItemBattleCfgMgr ItemBattleCfgMgr {get; }
    public ProfebsModelCfgMgr ProfebsModelCfgMgr {get; }
    public BulletCfgMgr BulletCfgMgr {get; }
    public HeroCfgMgr HeroCfgMgr {get; }
    public PrefabsEffectCfgMgr PrefabsEffectCfgMgr {get; }
    public SkillCfgMgr SkillCfgMgr {get; }
    public SkillLvCfgMgr SkillLvCfgMgr {get; }
    public MonsterCfgMgr MonsterCfgMgr {get; }
    public StatusCfgMgr StatusCfgMgr {get; }
    public DialogueCfgMgr DialogueCfgMgr {get; }
    public AttrConvertCfgMgr AttrConvertCfgMgr {get; }
    public MapCfgMgr MapCfgMgr {get; }
    public WeaponCfgMgr WeaponCfgMgr {get; }
    public MapRankCfgMgr MapRankCfgMgr {get; }
    public DropCfgMgr DropCfgMgr {get; }
    public GlobalDefCfgMgr GlobalDefCfgMgr {get; }
    public WaveCfgMgr WaveCfgMgr {get; }

    public Tables(System.Func<string, JSONNode> loader)
    {
        ItemCfgMgr = new ItemCfgMgr(loader("itemcfgmgr"));
        ItemBattleCfgMgr = new ItemBattleCfgMgr(loader("itembattlecfgmgr"));
        ProfebsModelCfgMgr = new ProfebsModelCfgMgr(loader("profebsmodelcfgmgr"));
        BulletCfgMgr = new BulletCfgMgr(loader("bulletcfgmgr"));
        HeroCfgMgr = new HeroCfgMgr(loader("herocfgmgr"));
        PrefabsEffectCfgMgr = new PrefabsEffectCfgMgr(loader("prefabseffectcfgmgr"));
        SkillCfgMgr = new SkillCfgMgr(loader("skillcfgmgr"));
        SkillLvCfgMgr = new SkillLvCfgMgr(loader("skilllvcfgmgr"));
        MonsterCfgMgr = new MonsterCfgMgr(loader("monstercfgmgr"));
        StatusCfgMgr = new StatusCfgMgr(loader("statuscfgmgr"));
        DialogueCfgMgr = new DialogueCfgMgr(loader("dialoguecfgmgr"));
        AttrConvertCfgMgr = new AttrConvertCfgMgr(loader("attrconvertcfgmgr"));
        MapCfgMgr = new MapCfgMgr(loader("mapcfgmgr"));
        WeaponCfgMgr = new WeaponCfgMgr(loader("weaponcfgmgr"));
        MapRankCfgMgr = new MapRankCfgMgr(loader("maprankcfgmgr"));
        DropCfgMgr = new DropCfgMgr(loader("dropcfgmgr"));
        GlobalDefCfgMgr = new GlobalDefCfgMgr(loader("globaldefcfgmgr"));
        WaveCfgMgr = new WaveCfgMgr(loader("wavecfgmgr"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        ItemCfgMgr.ResolveRef(this);
        ItemBattleCfgMgr.ResolveRef(this);
        ProfebsModelCfgMgr.ResolveRef(this);
        BulletCfgMgr.ResolveRef(this);
        HeroCfgMgr.ResolveRef(this);
        PrefabsEffectCfgMgr.ResolveRef(this);
        SkillCfgMgr.ResolveRef(this);
        SkillLvCfgMgr.ResolveRef(this);
        MonsterCfgMgr.ResolveRef(this);
        StatusCfgMgr.ResolveRef(this);
        DialogueCfgMgr.ResolveRef(this);
        AttrConvertCfgMgr.ResolveRef(this);
        MapCfgMgr.ResolveRef(this);
        WeaponCfgMgr.ResolveRef(this);
        MapRankCfgMgr.ResolveRef(this);
        DropCfgMgr.ResolveRef(this);
        GlobalDefCfgMgr.ResolveRef(this);
        WaveCfgMgr.ResolveRef(this);
    }
}

}
