
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace Table
{
public partial class WaveCfgMgr
{
    private readonly System.Collections.Generic.Dictionary<int, WaveCfg> _dataMap;
    private readonly System.Collections.Generic.List<WaveCfg> _dataList;
    
    public WaveCfgMgr(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, WaveCfg>();
        _dataList = new System.Collections.Generic.List<WaveCfg>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            WaveCfg _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = WaveCfg.DeserializeWaveCfg(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, WaveCfg> DataMap => _dataMap;
    public System.Collections.Generic.List<WaveCfg> DataList => _dataList;

    public WaveCfg GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public WaveCfg Get(int key) => _dataMap[key];
    public WaveCfg this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

