
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace Table
{
public sealed partial class WaveCfg : Luban.BeanBase
{
    public WaveCfg(JSONNode _buf) 
    {
        { if(!_buf["ID"].IsNumber) { throw new SerializationException(); }  ID = _buf["ID"]; }
        { if(!_buf["Group"].IsNumber) { throw new SerializationException(); }  Group = _buf["Group"]; }
        { if(!_buf["Index"].IsNumber) { throw new SerializationException(); }  Index = _buf["Index"]; }
        { if(!_buf["Name"].IsString) { throw new SerializationException(); }  Name = _buf["Name"]; }
        { if(!_buf["StartTime"].IsNumber) { throw new SerializationException(); }  StartTime = _buf["StartTime"]; }
        { if(!_buf["EndTime"].IsNumber) { throw new SerializationException(); }  EndTime = _buf["EndTime"]; }
        { if(!_buf["MonsterId"].IsNumber) { throw new SerializationException(); }  MonsterId = _buf["MonsterId"]; }
        { if(!_buf["Strength"].IsNumber) { throw new SerializationException(); }  Strength = _buf["Strength"]; }
        { if(!_buf["interval"].IsNumber) { throw new SerializationException(); }  Interval = _buf["interval"]; }
        { if(!_buf["RefreshCount"].IsNumber) { throw new SerializationException(); }  RefreshCount = _buf["RefreshCount"]; }
        { if(!_buf["LifeMax"].IsNumber) { throw new SerializationException(); }  LifeMax = _buf["LifeMax"]; }
        { if(!_buf["BossId"].IsNumber) { throw new SerializationException(); }  BossId = _buf["BossId"]; }
        { if(!_buf["CameraPos"].IsNumber) { throw new SerializationException(); }  CameraPos = _buf["CameraPos"]; }
        { if(!_buf["EventId"].IsNumber) { throw new SerializationException(); }  EventId = _buf["EventId"]; }
    }

    public static WaveCfg DeserializeWaveCfg(JSONNode _buf)
    {
        return new WaveCfg(_buf);
    }

    /// <summary>
    /// ID
    /// </summary>
    public readonly int ID;
    /// <summary>
    /// 组
    /// </summary>
    public readonly int Group;
    /// <summary>
    /// 波次
    /// </summary>
    public readonly int Index;
    /// <summary>
    /// 名字
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 开始时间
    /// </summary>
    public readonly float StartTime;
    /// <summary>
    /// 结束时间
    /// </summary>
    public readonly float EndTime;
    /// <summary>
    /// 怪物ID
    /// </summary>
    public readonly int MonsterId;
    /// <summary>
    /// 怪物强度
    /// </summary>
    public readonly float Strength;
    /// <summary>
    /// 刷新频率
    /// </summary>
    public readonly int Interval;
    /// <summary>
    /// 刷新数量
    /// </summary>
    public readonly int RefreshCount;
    /// <summary>
    /// 最大存活数量
    /// </summary>
    public readonly int LifeMax;
    /// <summary>
    /// 怪物bossid
    /// </summary>
    public readonly int BossId;
    /// <summary>
    /// 摄像机机位
    /// </summary>
    public readonly int CameraPos;
    /// <summary>
    /// 特殊地图事件
    /// </summary>
    public readonly int EventId;
   
    public const int __ID__ = -1502478709;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "Group:" + Group + ","
        + "Index:" + Index + ","
        + "Name:" + Name + ","
        + "StartTime:" + StartTime + ","
        + "EndTime:" + EndTime + ","
        + "MonsterId:" + MonsterId + ","
        + "Strength:" + Strength + ","
        + "interval:" + Interval + ","
        + "RefreshCount:" + RefreshCount + ","
        + "LifeMax:" + LifeMax + ","
        + "BossId:" + BossId + ","
        + "CameraPos:" + CameraPos + ","
        + "EventId:" + EventId + ","
        + "}";
    }
}

}

