
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace Table
{
public sealed partial class WeaponCfg : Luban.BeanBase
{
    public WeaponCfg(JSONNode _buf) 
    {
        { if(!_buf["ID"].IsNumber) { throw new SerializationException(); }  ID = _buf["ID"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["Active"].IsBoolean) { throw new SerializationException(); }  Active = _buf["Active"]; }
        { if(!_buf["skill"].IsNumber) { throw new SerializationException(); }  Skill = _buf["skill"]; }
        { if(!_buf["UnLock"].IsNumber) { throw new SerializationException(); }  UnLock = _buf["UnLock"]; }
        { if(!_buf["Damage"].IsNumber) { throw new SerializationException(); }  Damage = _buf["Damage"]; }
        { if(!_buf["Crit"].IsNumber) { throw new SerializationException(); }  Crit = _buf["Crit"]; }
        { if(!_buf["Penetrate"].IsNumber) { throw new SerializationException(); }  Penetrate = _buf["Penetrate"]; }
        { if(!_buf["Catapult"].IsNumber) { throw new SerializationException(); }  Catapult = _buf["Catapult"]; }
        { if(!_buf["ShotNum"].IsNumber) { throw new SerializationException(); }  ShotNum = _buf["ShotNum"]; }
        { if(!_buf["BulletNum"].IsNumber) { throw new SerializationException(); }  BulletNum = _buf["BulletNum"]; }
        { if(!_buf["Avatar"].IsString) { throw new SerializationException(); }  Avatar = _buf["Avatar"]; }
        { if(!_buf["UIAvatar"].IsString) { throw new SerializationException(); }  UIAvatar = _buf["UIAvatar"]; }
        { if(!_buf["WeaponSet"].IsString) { throw new SerializationException(); }  WeaponSet = _buf["WeaponSet"]; }
        { if(!_buf["Description"].IsString) { throw new SerializationException(); }  Description = _buf["Description"]; }
    }

    public static WeaponCfg DeserializeWeaponCfg(JSONNode _buf)
    {
        return new WeaponCfg(_buf);
    }

    /// <summary>
    /// ID
    /// </summary>
    public readonly int ID;
    /// <summary>
    /// 名字
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 激活
    /// </summary>
    public readonly bool Active;
    /// <summary>
    /// 技能
    /// </summary>
    public readonly int Skill;
    /// <summary>
    /// 解锁消耗
    /// </summary>
    public readonly int UnLock;
    /// <summary>
    /// 伤害
    /// </summary>
    public readonly int Damage;
    /// <summary>
    /// 暴击率
    /// </summary>
    public readonly float Crit;
    /// <summary>
    /// 穿透次数
    /// </summary>
    public readonly int Penetrate;
    /// <summary>
    /// 弹射次数
    /// </summary>
    public readonly int Catapult;
    /// <summary>
    /// 发射数量
    /// </summary>
    public readonly int ShotNum;
    /// <summary>
    /// 子弹数量
    /// </summary>
    public readonly int BulletNum;
    /// <summary>
    /// 外观
    /// </summary>
    public readonly string Avatar;
    /// <summary>
    /// UI外观
    /// </summary>
    public readonly string UIAvatar;
    public readonly string WeaponSet;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Description;
   
    public const int __ID__ = 801300616;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "name:" + Name + ","
        + "Active:" + Active + ","
        + "skill:" + Skill + ","
        + "UnLock:" + UnLock + ","
        + "Damage:" + Damage + ","
        + "Crit:" + Crit + ","
        + "Penetrate:" + Penetrate + ","
        + "Catapult:" + Catapult + ","
        + "ShotNum:" + ShotNum + ","
        + "BulletNum:" + BulletNum + ","
        + "Avatar:" + Avatar + ","
        + "UIAvatar:" + UIAvatar + ","
        + "WeaponSet:" + WeaponSet + ","
        + "Description:" + Description + ","
        + "}";
    }
}

}

